Update download location for vanilla kernels.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -556,7 +556,7 @@ Going to download the kernel source.
     if echo "$vanilla_opt" | grep "rc" > /dev/null 2>&1; then
       wget https://git.kernel.org/torvalds/t/linux-$vanilla_opt.tar.gz || die "Error(s) while fetching Linux source"
     else
-      wget https://www.kernel.org/pub/linux/kernel/v$MAJOR.x/linux-$vanilla_opt.tar.xz || die "Error(s) while fetching Linux source"
+      wget https://mirrors.edge.kernel.org/pub/linux/kernel/v$MAJOR.x/linux-$vanilla_opt.tar.xz || die "Error(s) while fetching Linux source"
     fi
     if echo "$vanilla_opt" | grep "rc" > /dev/null 2>&1; then
       tar -xzf linux-$vanilla_opt.tar.gz
